name: "Library Check-In"

on:
  schedule:
    # This cron syntax is UTC-based. 
    # Example: run at 14:00 UTC every day (which might be 8:00 AM Chicago Time CST-6 if DST not in effect).
    # Adjust to fit your needed times (and note Daylight Savings variations).
    - cron: "0 14 * * *"

  # (Optional) allow manual run via GitHub UI
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      # 4) Run the check_in.py script with the code argument
      - name: Run check in
        run: |
          python check_in.py 2SD
