name: "Library Check-In (Hourly :00 & :50)"

on:
  schedule:
    - cron: "0,50 * * * *"  # runs at minute 0 and 50 of every hour
  workflow_dispatch:         # optional manual trigger

jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Check in 2SD
        run: python check_in.py 2SD || true

      - name: Check in 59M
        run: python check_in.py 59M || true

      - name: Check in 6XT
        run: python check_in.py 6XT || true

      - name: Check in F2P
        run: python check_in.py F2P || true

      - name: Check in 4NY9
        run: python check_in.py 4NY9 || true
