name: "Library Check-In"

on:
  schedule:
    - cron: "0 15 * * *"  # 15:00 UTC -> 9:00am CST
    - cron: "0 18 * * *"  # 18:00 UTC -> 12:00pm CST
    - cron: "0 21 * * *"  # 21:00 UTC -> 3:00pm CST
    - cron: "0 0 * * *"   #  0:00 UTC -> 6:00pm CST
    - cron: "0 3 * * *"   # 21:00 UTC -> 9:00pm CST

  # (Optional) allow manual run via GitHub UI
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Check in 2SD
        run: python check_in.py 2SD

      - name: Check in 59M
        run: python check_in.py 59M

      - name: Check in 6XT
        run: python check_in.py 6XT
        
      - name: Check in F2P
        run: python check_in.py F2P
