name: "Library Check-In"

on:
  schedule:
    - cron: "0 15 * * *"  # 15:00 UTC -> 9:00 AM CST
    - cron: "0 18 * * *"  # 18:00 UTC -> 12:00 PM CST
    - cron: "0 21 * * *"  # 21:00 UTC -> 3:00 PM CST
    - cron: "0 0 * * *"   # 00:00 UTC -> 6:00 PM CST
    - cron: "0 3 * * *"   # 03:00 UTC -> 9:00 PM CST
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run check_in.py (time-based)
        run: python time_based_checkin.py
