name: "Library Check-In (Every 5 Minutes)"

on:
  schedule:
    - cron: "*/5 * * * *"   # runs at minute 0,5,10,15,... every hour
  # optional: let you run it manually in the Actions tab
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      # 1. Check in 2SD
      - name: Check in 2SD
        run: python check_in.py 2SD || true  # "|| true" ensures we don't fail the job if there's an error

      # 2. Check in 59M
      - name: Check in 59M
        run: python check_in.py 59M || true

      # 3. Check in 6XT
      - name: Check in 6XT
        run: python check_in.py 6XT || true

      # 4. Check in F2P
      - name: Check in F2P
        run: python check_in.py F2P || true
