name: "Library Check-In"

on:
  schedule:
    - cron: "0 15 * * *"  # 15:00 UTC -> 9:00am CST
    - cron: "0 18 * * *"  # 18:00 UTC -> 12:00pm CST
    - cron: "0 21 * * *"  # 21:00 UTC -> 3:00pm CST
    - cron: "0 0 * * *"   #  0:00 UTC -> 6:00pm CST
    - cron: "0 3 * * *"   # 21:00 UTC -> 9:00pm CST

  # (Optional) allow manual run via GitHub UI
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      # 4) Run the check_in.py script with the code argument
      - name: Run check in
        run: |
          python check_in.py 2SD
          python check_in.py 59M
          python check_in.py 6XT
          python check_in.py F2P
