name: "Library Check-In (Hourly :00 & :50)"

on:
  schedule:
    - cron: "25,55 * * * *"  # runs at minute 25 and 55 of every hour
  workflow_dispatch:

jobs:
  checkin_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Check in 1
        run: python check_in.py 6XT || true

      - name: Check in 2
        run: python check_in.py J74 || true

      - name: Check in 3
        run: python check_in.py D3A || true

      - name: Check in 4
        run: python check_in.py F2P || true

      - name: Check in 5
        run: python check_in.py Y2L || true
